<?php
#ARCHIVO QUE CONTIENE LAS PRIMERAS CONFIGURACIONES QUE SE DEBEN HACER AL SISTEMA
#NO INCLUYE CONEXIONES NI CONTRASEÑAS POR QUE ESTAS CONFIGURACIONES ESTAN EN GLOBAL
#Y POR SEGURIDAD NO SE ANEXAN Y SE LISTAN AQUI

#NOMBRE DE LA CARPETA DEL PROYECTO, ESTA ES PUBLICA
$name_proyect = 'orfeounity';


?>